version: "3.7"

services: 
  express:
    container_name: express
    build: 
      context: .
      args: 
        NODE_ENV: production
    ports: 
      - 3000:3000
    environment: 
      - NODE_ENV='production'
