version: "3.7"

services: 
  express:
    build: 
      args: 
        NODE_ENV: development
    environment: 
      - NODE_ENV='development'
    volumes: 
      - ./server:/app/server
    command: npm run dev